enum EstadoOrden {
  PENDIENTE
  PAGADA
  COMPLETADA
  CANCELADA
}

type Orden @key(fields: "id") {
  id: ID!
  estado: EstadoOrden!
  usuarioId: ID!
  usuario: Usuario @external
  total: Float!
  pedidos: [Pedido] @external
  pagos: [Pago] @external
  creadoEn: DateTime!
  actualizadoEn: DateTime!
}

input CrearOrdenInput {
  usuarioId: ID!
}

input ActualizarOrdenInput {
  estado: EstadoOrden
}

extend type Query {
  ordenes: [Orden!]!
  orden(id: ID!): Orden
}

extend type Mutation {
  crearOrden(input: CrearOrdenInput!): Orden!
  actualizarOrden(id: ID!, input: ActualizarOrdenInput!): Orden!
  eliminarOrden(id: ID!): Boolean!
}
