type Pedido @key(fields: "id") {
  id: ID!
  producto: String!
  descripcion: String
  cantidad: Int!
  precioUnitario: Float!
  subtotal: Float!
  usuarioId: ID!
  usuario: Usuario @external
  ordenId: ID
  orden: Orden @external
  creadoEn: DateTime!
  actualizadoEn: DateTime!
}

input CrearPedidoInput {
  producto: String!
  descripcion: String
  cantidad: Int!
  precioUnitario: Float!
  usuarioId: ID!
  ordenId: ID
}

input ActualizarPedidoInput {
  producto: String
  descripcion: String
  cantidad: Int
  precioUnitario: Float
  ordenId: ID
}

extend type Query {
  pedidos(usuarioId: ID, ordenId: ID): [Pedido!]!
  pedido(id: ID!): Pedido
}

extend type Mutation {
  crearPedido(input: CrearPedidoInput!): Pedido!
  actualizarPedido(id: ID!, input: ActualizarPedidoInput!): Pedido!
  eliminarPedido(id: ID!): Boolean!
}
