extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable"])

enum MetodoPago {
  TARJETA
  EFECTIVO
  TRANSFERENCIA
  OTRO
}

enum EstadoPago {
  PENDIENTE
  APROBADO
  RECHAZADO
  REEMBOLSADO
}

type Pago @key(fields: "id") {
  id: ID!
  monto: Float!
  metodo: MetodoPago!
  estado: EstadoPago!
  referencia: String
  ordenId: ID!
  creadoEn: String!
  actualizadoEn: String!
}

type Query {
  pagos(ordenId: ID): [Pago!]!
  pago(id: ID!): Pago
}

type Mutation {
  crearPago(monto: Float!, metodo: String!, referencia: String, ordenId: ID!): Pago!
  actualizarPago(id: ID!, monto: Float, metodo: String, estado: String, referencia: String): Pago!
  eliminarPago(id: ID!): Boolean!
}
