extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable"])

type Pedido @key(fields: "id") {
  id: ID!
  producto: String!
  descripcion: String
  cantidad: Int!
  precioUnitario: Float!
  subtotal: Float!
  usuarioId: ID!
  ordenId: ID
  creadoEn: String!
  actualizadoEn: String!
}

type Query {
  pedidos(usuarioId: ID, ordenId: ID): [Pedido!]!
  pedido(id: ID!): Pedido
}

type Mutation {
  crearPedido(producto: String!, descripcion: String, cantidad: Int!, precioUnitario: Float!, usuarioId: ID!, ordenId: ID): Pedido!
  actualizarPedido(id: ID!, producto: String, descripcion: String, cantidad: Int, precioUnitario: Float, ordenId: ID): Pedido!
  eliminarPedido(id: ID!): Boolean!
}
